name: Base Image Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Every monday at 10am
  schedule:
    - cron: '0 10 * * 1'

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: pressapi
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: pressapi/php-alpine:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
